language: c++

# add branches you want to triger CI
branches:
  only:
    - master

sudo: required

services:
  - docker

compiler:
  - g++

# TODO: we can auto-build and publish this docker image
# see https://docs.docker.com/docker-cloud/builds/automated-build
env:
  global:
  matrix:
    - CONTAINER_NAME="comanche-build-fedora27"
      DOCKERIMG="fedora:27" 
      HOSTMODULE="-v /lib/modules:/lib/modules:ro -v /usr/src:/usr/src:ro"
    - CONTAINER_NAME="comanche-build-ubuntu1604"
      DOCKERIMG="ubuntu:16.04"  

# comanche requires cmake 3.6.2 (to build google/benchmark)
# for local building testing, remener to run git submodule init/update
# https://stackoverflow.com/questions/33013539/docker-loading-kernel-modules
install:
  - docker run -d --name ${CONTAINER_NAME} --privileged --cap-add=ALL
    -v $(pwd):/travis ${HOSTMODULE}
    ${DOCKERIMG}
    tail -f /dev/null
  - docker ps

# note: limit job number to 2 to avoid out-of-memory for rocksdb build
script:
  - docker exec -t ${CONTAINER_NAME} bash -c "
    cd /travis ;
    make;"

after_success:
  - echo ' complete'
